#!/usr/bin/python

import os
from optparse import OptionParser
import BaseHTTPServer
from SimpleHTTPServer import SimpleHTTPRequestHandler
from SocketServer import ThreadingMixIn
import json

class MyReqHandler(SimpleHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/post-notes":
            length = int(self.headers.getheader('content-length'))
            data = self.rfile.read(length)
            # Pretty-print JSON to notes.json
            jsdata = json.loads(data)
            pretty = json.dumps(jsdata, sort_keys=True, indent=4) + "\n"
            file("notes.json", "w").write(pretty)
            self.send_response(200)
        else:
            self.send_error(403)

class MyHTTPServer(ThreadingMixIn, BaseHTTPServer.HTTPServer): pass

def main():
    global options

    parser = OptionParser()
    parser.add_option("-p", "--port", action = "store", dest = "port",
                      type = "int", default = 8000, help = "HTTP port")
    parser.add_option("-a", "--any", action = "store_true", dest = "any",
                      default = False, help = "Allow connections from any IP")
    (options, args) = parser.parse_args()
    if len(args):
        parser.error("Unexpected arguments")

    print "Serving %s on port %d to %s" % \
        (os.getcwd(), options.port, "any IP" if options.any else "localhost")
    bind = ("" if options.any else "localhost", options.port)
    MyHTTPServer(bind, MyReqHandler).serve_forever()

if __name__ == "__main__":
    main()
