#!/usr/bin/python -3

# Generate throughput graphs of mailbench results

import plot
import common

d = common.argv_to_table()

plot.Gnuplot(d, x="iv.cores", y="dv.messages/sec",
             layer=("iv.alt",)). \
             data()
