#!/usr/bin/env python

import argparse
import sys
import textformat
import data

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument('file', type=open, default=sys.stdin)
args = arg_parser.parse_args()

t = data.Table(textformat.parse(args.file))
cols = list(t.properties().prop('name'))
print '\t'.join(col.replace(' ', '_') for col in cols)
for row in t:
    print '\t'.join(str(row[col]) if row[col] is not None else '?'
                    for col in cols)
